#!/usr/bin/env zsh

export LANG='en_US.UTF-8'
export EDITOR='nvim'

export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_STATE_HOME="$HOME/.local/state"
export XDG_CACHE_HOME="$HOME/.cache"

export ZDOTDIR="$XDG_CONFIG_HOME/zsh"

path=(
  "$HOME/bin"
  "$HOME/.local/bin"
  "/usr/local/go/bin"
  $path
)

# Snap (workaround for https://qiita.com/sameyasu/items/072882ee92bca54906d8)
if [ -f '/etc/profile.d/apps-bin-path.sh' ]; then
  source '/etc/profile.d/apps-bin-path.sh'
fi

# Cargo
if [ -f "$HOME/.cargo/env" ]; then
  source "$HOME/.cargo/env"
fi

# Deno
if [ -d "$HOME/.deno" ]; then
  export DENO_INSTALL="$HOME/.deno"
  export PATH="$DENO_INSTALL/bin:$PATH"
fi
