#!/usr/bin/env zsh

SCRIPTS_DIR="$ZDOTDIR/scripts"

source "$SCRIPTS_DIR/load_zinit.zsh"
source "$SCRIPTS_DIR/set_options.zsh"
source "$SCRIPTS_DIR/set_aliases.zsh"
source "$SCRIPTS_DIR/local.zsh"

source <(mise activate zsh)
source <(starship init zsh)

# 端末のウィンドウやタブのタイトル設定
zstyle ':prezto:module:terminal' auto-title 'yes'
zstyle ':prezto:module:terminal:window-title' format '%n@%m: %s'
zstyle ':prezto:module:terminal:tab-title' format '%m: %s'
zstyle ':prezto:module:terminal:multiplexer-title' format '%s'
zinit ice lucid blockf
zinit snippet PZTM::terminal

# Lazy load
zinit ice wait lucid null \
  atinit'source "$SCRIPTS_DIR/lazy/entrypoint.zsh"'
zinit light 'zdharma-continuum/null'
